# MODELSTAR CONFIGURATION FILE
---
sessions:
    - name: snowflake-test
      connector: snowflake
      config:
          account: <account>
          username: <username>
          password: <password>
          database: <database>
          schema: <schema>
          stage: <stage>
          warehouse: <warehouse>
