# Modelstar project details

[snowflake]

account = "<account>" 
username = "<username>" 
password = "<password>" 
role = "<role>"
database = "<database>" 
schema = "<schema>"
warehouse = "<warehouse>" 